name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload static site
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'  # Make sure this is where index.html lives

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
